import React from "react";
import { Link } from "react-router-dom";

const kpis = [
  ["▥", "Connected Corridors", "12", "COA monitored", "blue"],
  ["✓", "Verified Windows", "86", "Next 30 days", "green"],
  ["▣", "High Traffic Sections", "4", "Additional constraints", "orange"],
  ["◷", "Average Availability", "78%", "Illustrative demo view", "purple"],
];

const Dashboard = () => <div className="dashboard-page">
  <div className="dashboard-alert"><b>▲ &nbsp; Important:</b> Planned maintenance blocks for Northern Corridor on 10 Sep 2026. Kindly review and coordinate.<Link to="/block-planning">View Details →</Link><button aria-label="Dismiss alert">×</button></div>
  <div className="dashboard-heading"><div><span>RAILWAY OPERATIONS</span><h1>Corridor &amp; Block Availability</h1><p>Verified maintenance opportunities after applying train timetable and goods forecast inputs.</p></div><div className="dashboard-quote">“Viksit Bharat ke live Viksit Rail”<small>— Ministry of Railways</small></div></div>
  <div className="dashboard-layout"><main>
    <div className="dashboard-kpis">{kpis.map(([icon, label, value, note, tone]) => <div className={`dashboard-kpi ${tone}`} key={label}><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{note}</small><Link to="/corridor-availability">View {label.includes("Corridor") ? "Corridors" : label.includes("Window") ? "Windows" : "Analytics"} →</Link></div></div>)}</div>
    <section className="dashboard-panel timetable-panel"><div className="panel-heading"><div><h2>Corridor timetable overlay</h2><p>CR-NDL-04 • Time runs from 22:00 to 04:00</p></div><div className="legend"><span className="express">Express Train</span><span className="passenger">Passenger Train</span><span className="goods">Goods Train</span><span className="maintenance">Maintenance Window</span><Link to="/weekly-planning">View Full Schedule →</Link></div></div><div className="timeline"><div className="timeline-hours"><b></b>{["22:00", "23:00", "00:00", "01:00", "02:00", "03:00", "04:00"].map((hour) => <span key={hour}>{hour}</span>)}</div>{[["Train timetable", [["Express", "8%", "28%", "red"], ["Goods forecast", "72%", "26%", "red"]]], ["Engineering", [["ENG-104", "35%", "25%", "blue"]]], ["S&T", [["ST-208", "38%", "27%", "purple"]]], ["AI coordinated", [["Recommended shared block", "32%", "32%", "green"]]]].map(([label, blocks]) => <div className="timeline-row" key={label}><b>{label}</b><div className="track">{blocks.map(([name, left, width, tone]) => <span className={`slot ${tone}`} style={{ left, width }} key={name}>{name}</span>)}</div></div>)}</div></section>
    <div className="corridor-cards">{[["CR-NDL-04", "New Delhi — Ghaziabad", "Available", "23:30–02:45", "Medium"], ["CR-KAN-12", "Kanpur — Prayagraj", "Limited", "01:15–02:30", "High"], ["CR-BPL-07", "Bhopal — Itarsi", "Available", "00:30–03:30", "Low"]].map(([id, route, status, time, traffic]) => <div className="corridor-card" key={id}><div><strong>{id}</strong><i>▥</i></div><small>{route}</small><p><em className={status.toLowerCase()}>{status}</em><b>{time}</b></p><small>Traffic density: {traffic}</small><Link to="/corridor-availability">View Details →</Link></div>)}<div className="network-card"><div className="network-card-heading"><strong>Network Overview</strong><Link to="https://www.google.com/maps/search/Indian+Railways+New+Delhi" target="_blank" rel="noreferrer">Open in Google Maps ↗</Link></div><iframe title="Indian Railways network map" src="https://www.google.com/maps?q=Indian+Railways+New+Delhi&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><Link to="/corridor-availability">View Network Map →</Link></div></div>
  </main><aside className="dashboard-actions"><section className="dashboard-panel quick-actions"><h2>⚙ Quick Actions</h2><Link className="action-primary" to="/block-planning">◉ &nbsp; Recommend Maintenance Window</Link><Link className="action-success" to="/ai-priority">↻ &nbsp; Run AI Analysis</Link><Link to="/reports">▧ &nbsp; Generate Report</Link><Link to="/weekly-planning">↥ &nbsp; Upload Timetable</Link><Link to="/monthly-planning">▣ &nbsp; Goods Forecast Input</Link></section><section className="dashboard-panel recent-alerts"><div><h2>⦿ Recent Alerts</h2><Link to="/conflict-resolution">View All</Link></div><p><i className="alert-red"/>Block conflict detected <small>2 hours ago</small></p><p><i className="alert-green"/>Maintenance window approved <small>5 hours ago</small></p><p><i className="alert-orange"/>High traffic alert (CR-KAN) <small>6 hours ago</small></p><p><i className="alert-green"/>System sync completed <small>8 hours ago</small></p></section></aside></div>
  <footer className="dashboard-footer"><div className="rail-silhouette"><span>▰▰▰▰▰</span><b>INDIAN RAILWAYS</b><small>● Lifeline of the Nation</small></div><nav>About Us　|　Policies　|　RTI　|　Tenders　|　Citizen Charter　|　Feedback　|　Sitemap　|　Contact Us</nav><span>© 2026 Ministry of Railways, Government of India. All Rights Reserved.</span></footer>
</div>;
export default Dashboard;
